Branch dg update
AY2122S1-CS2103T-F12-2/tp pull request #216
Opened 2021-11-02 16:13 UTC by yunpeng1234

![image](https://user-images.githubusercontent.com/58326594/139899114-c683dd94-9e7b-4553-93f0-2b9fae10d561.png)

![image](https://user-images.githubusercontent.com/58326594/139899467-e442f879-f22b-45c8-af11-0212a99a02c4.png)

![image](https://user-images.githubusercontent.com/58326594/139899951-29998994-3a74-4b0f-b189-e19cf7bdee0f.png)

![image](https://user-images.githubusercontent.com/58326594/139900500-85ee6483-334a-4a80-93bc-e4ab2b973402.png)

Might be the same as @Chang-CH pr but just to compare see if they are right

2021-11-03 13:27 UTC, yunpeng1234 commented
Guys help check the UML diagram thanks

2021-11-03 19:22 UTC, Jeromesyl commented
For Model, there should be a VersionedInternWatcher that inherits from InternWatcher. VersionedInternWatcher actually replaces InternWatcher in ModelManager, so I think that the associations from ModelManager and UniquePersonList should be connected to VersionedInternWatcher instead?

2021-11-04 03:02 UTC, Chang-CH commented
There are still traces of `person`. I already have edited PUML's on my PR.

2021-11-04 03:03 UTC, Chang-CH requested changes
Unless my PUML messed up as well these should be duplicate changes.

2021-11-04 03:03 UTC, Chang-CH commented on docs/diagrams/ModelClassDiagram.puml
>  Class UniquePersonList
`Person` here

2021-11-04 03:03 UTC, Chang-CH commented on docs/diagrams/UiClassDiagram.puml
>  MainWindow *-down-> "1" PersonListPanel
`Person` here

2021-11-04 03:38 UTC, yunpeng1234 commented on docs/diagrams/UiClassDiagram.puml
>  MainWindow *-down-> "1" PersonListPanel
Thats our ui component no?

2021-11-04 05:45 UTC, yunpeng1234 commented
New Diagrams

*DeleteSeq*
![image](https://user-images.githubusercontent.com/58326594/140263811-3d30ead9-304a-4ac6-9111-b1052ac703df.png)

*DeleteAllSeq*
![image](https://user-images.githubusercontent.com/58326594/140263913-c2dcd83a-aef7-47e1-905a-3f22e2ab3ab7.png)

*EditAllSeq*
![image](https://user-images.githubusercontent.com/58326594/140264056-3346ccd5-124d-465d-9f35-342def11f8e9.png)

*ModelClass*
![image](https://user-images.githubusercontent.com/58326594/140264112-395f828a-2549-438f-b75e-75a27ef06a17.png)

2021-11-04 06:32 UTC, Chang-CH approved these changes
LGTM

2021-11-04 06:32 UTC, Chang-CH approved these changes
LGTM

2021-11-04 12:15 UTC, merged